displayName: Subfilter
summary: Rewrites the HTTP response based on predefined regex rules
type: middleware
import: github.com/dirtycajunrice/traefik-subfilter-plugin
compatibility: TODO
testData:
  lastModified: true
  rewrites:
    - regex: "bar"
      replacement: "foo"
